Add riscv-rt to workspace
rust-embedded/riscv pull request #151
Opened 2023-11-17 15:16 UTC by romancardenas

This PR adds [`riscv-rt`](https://github.com/rust-embedded/riscv-rt) to this workspace. I'm still working on fine-tuning the CI, let me know your opinion and I'll push it to the PR 😄

2023-11-20 13:36 UTC, romancardenas commented
@rust-embedded/riscv good to go! Take a look and let me know if I forgot something

2023-11-27 13:58 UTC, jessebraham requested changes
Few little nitpicks but otherwise LGTM!

2023-11-27 13:58 UTC, jessebraham commented on riscv-rt/README.md
> +[![Build Status](https://travis-ci.org/rust-embedded/riscv-rt.svg?branch=master)](https://travis-ci.org/rust-embedded/riscv-rt)
Is Travis CI actually used? Doesn't appear to be, I'm guessing this is just an artifact from the past.

2023-11-27 13:58 UTC, jessebraham commented on riscv-rt/macros/Cargo.toml
> +repository = "https://github.com/rust-embedded/riscv-rt"
```suggestion
repository = "https://github.com/rust-embedded/riscv"
```

2023-11-27 13:58 UTC, jessebraham commented on riscv/README.md
> +[![Build Status](https://travis-ci.org/rust-embedded/riscv.svg?branch=master)](https://travis-ci.org/rust-embedded/riscv)
See above.

2023-11-27 15:22 UTC, romancardenas commented
Thanks for your review @jessebraham ! I addressed all your comments and adapted the general `README.md` file from [`cortex-m`](https://github.com/rust-embedded/cortex-m)

2023-11-27 15:28 UTC, jessebraham approved these changes
Thanks for making those changes, LGTM!

2023-11-27 16:50 UTC, merged