Update for embedded-hal to 1.0.0-rc.2
rust-embedded/riscv pull request #159
Opened 2023-11-29 23:28 UTC by purplethunder

embedded-hal 1.0.0-rc.2 introduced [backwards incompatible changes](https://github.com/rust-embedded/embedded-hal/commit/4ec58c85d81a191a0efddcf7269d0a4c753b2b45) that break riscv builds.  This change pins the crate to 1.0.0-rc.1.

```
error[E0432]: unresolved import `embedded_hal::delay::DelayUs`
 --> riscv/src/delay.rs:3:5
  |
3 | use embedded_hal::delay::DelayUs;
  |     ^^^^^^^^^^^^^^^^^^^^^-------
  |     |                    |
  |     |                    help: a similar name exists in the module: `DelayNs`
  |     no `DelayUs` in `delay`

For more information about this error, try `rustc --explain E0432`.
```

2023-11-29 23:38 UTC, MabezDev commented
I don't think we should accept this PR, instead we should upgrade riscv to the newest release candidate. Would you mind PRing that instead?

2023-11-30 08:28 UTC, romancardenas requested changes
Looks good to me!! I left you a couple of comments, please address them before accepting the PR

2023-11-30 08:28 UTC, romancardenas commented on riscv/src/delay.rs
> +        let us_64: u64 = ns.into();
Please, rename this to `ns_64`

2023-11-30 08:28 UTC, romancardenas commented on riscv/src/delay.rs
>      fn delay_us(&mut self, us: u32) {
Can't we use the default implementation of this method?

2023-11-30 15:50 UTC, romancardenas commented
Hmm... maybe we need to bump riscv-rt to 1.60?

2023-11-30 15:53 UTC, romancardenas commented
You will probably also need to update the CI to make it pass: https://github.com/rust-embedded/riscv/blob/f8c39238c815af9ca92ce945c0dc4ab83c58a004/.github/workflows/riscv-rt.yaml#L14

2023-12-01 11:15 UTC, romancardenas commented
Seems that the issue comes with `riscv-target`, used for building the `riscv-rt` crate and check the different RISC-V extensions...

I'll try to develop a quick solution to stop using this dependency and allow us to leave the MSRV to 1.60

2023-12-02 12:55 UTC, romancardenas commented
Closing as #160 now solves this

2023-12-02 12:55 UTC, closed without merging